<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

remove_action( 'genesis_after_post_content', 'genesis_post_meta' );
//* Remove the entry meta in the entry header (requires HTML5 theme support)
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
//* Remove the entry title (requires HTML5 theme support)
remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
//* Remove the post content (requires HTML5 theme support)
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );
//* Remove the post image (requires HTML5 theme support)
remove_action( 'genesis_entry_content', 'genesis_do_post_image', 8 );
//* Remove the entry header markup (requires HTML5 theme support)
remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_open', 5 );
remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_close', 15 );
//* Remove the entry footer markup (requires HTML5 theme support)
remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_open', 5 );
remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_close', 15 );

add_action( 'genesis_entry_content', 'equipment_new_loop');
function equipment_new_loop() {
	require(CHILD_DIR . '/template-parts/equipment-loop-single.php');
}

add_action('genesis_before_entry', 'equip_entry_wrapper'); 

function equip_entry_wrapper() {
	global $wp_query;
	$theCurrentpost = $wp_query->current_post;
	
	if($theCurrentpost % 3 == 0){
	echo '<div class="one-third first">';
	}
	else{
	echo '<div class="one-third">';
	}
}

add_action('genesis_after_entry', 'equip_entry_wrapper_close'); 

function equip_entry_wrapper_close() {
	global $wp_query;
	$theCurrentpost = $wp_query->current_post;
	
	if(($theCurrentpost+1) % 3 == 0){
	echo '</div><div class="clearfix"></div>';
	}
	else{
	echo '</div>';
	}
}


// Initialize Genesis.
genesis();